name: Build Shimboot Grunt
    strategy: 
      matrix:
        board: [grunt]  # This ensures only the 'grunt' board is built

    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 4096
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'

      - name: download repo
        uses: actions/checkout@v4
      
      - name: run build
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo DEBUG=1 ./build_complete.sh ${{ matrix.board }} distro=ubuntu desktop=kde compress_img=1 quiet=1

      - name: upload img
        uses: actions/upload-artifact@v4
        with:
          name: shimboot_${{ matrix.board }}
          path: data/shimboot_${{ matrix.board }}.bin
          compression-level: 7
  
      - name: create release
        uses: softprops/action-gh-release@v1
        
